[project]
name = "script-selenium"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "selenium>=4.33.0",
    "webdriver-manager>=4.0.2",
]
